import type { Experience, Leadership, Recommendation } from "./types";

export const experience: Experience[] = [
  {
    id: "cdot",
    org: "Colorado Department of Transportation",
    team: "Staff Bridge Branch · Bridge Asset Management",
    location: "Denver, CO",
    kind: "Internship",
    visibility: "public",
    current: false,
    roles: [{ title: "Engineering Intern", start: "May 2026", end: "Summer 2026" }],
    summary: "Bridge inventory, inspection, and clearance data for a statewide inventory of 3,500+ bridges, plus time in the field with inspectors.",
    highlights: [
      "Wrote SQL queries in SSMS against inspection, project, and vertical-clearance databases",
      "Reviewed plan sets for 16 projects to identify structures and their planned treatments, updating records to SNBI",
      "Built CDOT Compass, which CDOT published as a 2026 Lean Everyday Idea",
    ],
    details: [
      "Cross-referenced structure IDs across SIMSA, OnBase, and OTIS to fix discrepancies.",
      "Joined licensed bridge inspectors and recorded vertical clearances with intern teams; watched girder erection on I-70 Floyd Hill.",
      "Funded in part by Greene Center summer internship funding.",
    ],
    tools: ["SQL", "SSMS", "SNBI", "OpenRoads Designer", "React", "TypeScript"],
    relatedProjects: ["cdot-bridge-asset-management", "cdot-compass"],
    needs: ["Region 2 VRI/AR workflow details", "Supervisor recommendation", "Confirm end date"],
  },
  {
    id: "agr",
    org: "AGR Sensors",
    team: "CropSight AI pipeline",
    location: "Rochester, NY · Remote",
    kind: "Internship",
    visibility: "public",
    current: true,
    roles: [{ title: "Data Research Intern", start: "Jan 2026", end: "Present" }],
    summary: "Structuring and validating the knowledge base behind an AI crop-disease diagnosis system.",
    highlights: [
      "Audited 250+ document chunks from 22 reference books to full page coverage, zero schema errors",
      "Catalogued 212 disease and pest entries as ML-ready JSON with Python checks",
      "Keep a multi-contributor Git repository in sync",
    ],
    tools: ["Python", "JSON Schema", "Git", "rclone"],
    relatedProjects: ["cropsight-knowledge-base"],
  },
  {
    id: "handshake",
    org: "Handshake",
    team: "AI Fellowship",
    location: "Remote",
    kind: "Fellowship",
    visibility: "public",
    current: true,
    roles: [{ title: "AI Fellow", start: "Jun 2026", end: "Present" }],
    summary: "Writing and reviewing structured task prompts for AI training data on real desktop workflows.",
    highlights: ["Write and review prompts against quality guidelines", "Validate labeled data for consistency"],
    tools: ["Data labeling", "Prompt review"],
  },
  {
    id: "it-center",
    org: "University of Rochester IT Center",
    location: "Rochester, NY",
    kind: "Campus job",
    visibility: "public",
    current: true,
    roles: [
      { title: "Level 2 Training Coordinator (Student Lead)", start: "Jan 2026", end: "Present", note: "Promoted" },
      { title: "Help Desk Technician", start: "Jan 2025", end: "Jun 2026" },
    ],
    summary: "Started on the help desk; a year later, promoted to mentor new staff and take the harder cases.",
    highlights: [
      "Handle escalated network registration, wired/wireless, NetID/Duo, and malware cases (75+ ServiceNow tickets a week)",
      "Mentor Level 1 staff and help shape the student training program",
    ],
    tools: ["ServiceNow", "Windows", "macOS", "Linux"],
  },
  {
    id: "peer-advisor",
    org: "Center for Advising Services, University of Rochester",
    location: "Rochester, NY",
    kind: "Campus job",
    visibility: "public",
    current: true,
    roles: [{ title: "Peer Advisor", start: "", end: "Present" }],
    summary: "Helping fellow students with academic planning.",
    highlights: ["Advise students on academic planning and campus resources"],
    tools: ["Advising"],
    needs: ["Start date", "One concrete detail about the role"],
  },
  {
    id: "admissions",
    org: "[VERIFY OFFICE]",
    location: "Rochester, NY",
    kind: "Campus job",
    visibility: "hidden",
    current: true,
    roles: [{ title: "[VERIFY TITLE]", start: "[VERIFY]", end: "Present" }],
    summary: "[VERIFY DESCRIPTION]",
    highlights: [],
    tools: [],
    needs: ["Exact title, office, dates, and description"],
  },
  {
    id: "uwp",
    org: "Ugandan Water Project",
    team: "Development Office · Schwartz Community-Based Internship",
    location: "Lima, NY",
    kind: "Internship",
    visibility: "public",
    current: false,
    roles: [{ title: "Development Intern", start: "Jun 2025", end: "Aug 2025" }],
    summary: "Fundraising, data, and partner outreach for a nonprofit building clean-water infrastructure in Uganda. My first look at how water projects get funded.",
    highlights: [
      "Contacted 100+ donors and prospective corporate sponsors by phone and email, helping raise $5K+",
      "Cleaned and organized donor-database records",
      "Ran communications for the 3rd Annual UWP Golf Tournament (July 2025)",
    ],
    tools: ["CRM data", "Excel", "Illustrator", "Canva"],
  },
  {
    id: "rcl",
    org: "University of Rochester River Campus Libraries",
    team: "Open publishing",
    location: "Rochester, NY",
    kind: "Internship",
    visibility: "public",
    current: false,
    roles: [{ title: "Editorial Assistant Intern", start: "May 2025", end: "Aug 2025" }],
    summary: "Editorial and web work for three UR journals: Blake/An Illustrated Quarterly, InVisible Culture, and Working Papers in the Language Sciences.",
    highlights: [
      "Designed the Summer 2025 cover of Blake/An Illustrated Quarterly",
      "Created article metadata and reviewed DOI integration",
      "Edited journal stylesheets in HTML/CSS on Open Journal Systems and PubPub",
    ],
    tools: ["HTML/CSS", "OJS", "PubPub", "InDesign"],
    relatedProjects: ["blake-quarterly-cover"],
  },
];

export const leadership: Leadership[] = [
  { id: "nsbe-pubs", org: "NSBE Region 1 Upstate Zone", role: "Publications Chair", level: "Elected", start: "May 2026", end: "Present", group: "Engineering community", visibility: "public", detail: "Design and maintain the zone’s visual identity, a shared Canva design system for chapters, and promotion for the Regional Leadership and Fall Zone conferences." },
  { id: "nsbe-senator", org: "National Society of Black Engineers, University of Rochester chapter", role: "Senator", level: "Elected", start: "Apr 2025", end: "Jun 2026", group: "Engineering community", visibility: "public", detail: "The chapter’s voice in NSBE governance: liaison to national leadership, voting on national ballots, and representing the chapter in official meetings and at the 2026 convention." },
  { id: "foreverbetter", org: "For Ever Better: The Campaign for the University of Rochester", role: "Student Alumni Ambassadors Campaign Chair; Campaign Steering Committee member", level: "Appointed", start: "Sep 2025", end: "Present", group: "University", visibility: "public", detail: "Invited by the university’s Senior Vice President for Advancement to serve on the steering committee of the university’s $1.75 billion campaign, and to help host the public campaign launch in September 2025." },
  { id: "saa", org: "Student Alumni Ambassadors, University of Rochester", role: "Ambassador", level: "Selected", start: "Mar 2025", end: "Present", group: "University", visibility: "public", detail: "Alumni events including Meliora Weekend, campus visits, and student–alumni connections." },
  { id: "unibooth", org: "UniBooth", role: "Co-founder, COO & CFO", level: "Co-founder", start: "Sep 2025", end: "Present", group: "University", visibility: "public", detail: "Operations, financial planning, and the business model for a student photo-booth startup." },
  { id: "techgirls-aac", org: "TechGirls Alumnae Advisory Council (U.S. Department of State)", role: "Core Council Member", level: "Selected", start: "2024", end: "2025", group: "Global", visibility: "public", detail: "Community Building Committee (2024) and Programming Committee (2025): peer mentoring for new TechGirls and alumnae events across 25+ countries." },
  { id: "iso-mentor", org: "International Services Office, University of Rochester", role: "International Student Mentor", level: "Selected", start: "Aug 2025", end: "Present", group: "Mentoring & teaching", visibility: "public", detail: "One-on-one mentoring, goal setting, and workshops for new international students." },
  { id: "nextgen4all", org: "NextGen4All", role: "College-access Mentor", level: "Volunteer", start: "Oct 2024", end: "Present", group: "Mentoring & teaching", visibility: "public", detail: "Helping high school students in Rwanda through university applications." },
  { id: "bgc", org: "Boys & Girls Club, Rochester", role: "Tutor & Mentor", level: "Volunteer", start: "Feb 2025", end: "Present", group: "Mentoring & teaching", visibility: "public", detail: "Math and science tutoring and study skills." },
  { id: "ewb", org: "Engineers Without Borders, University of Rochester", role: "Member", level: "Member", start: "", end: "", group: "Engineering community", visibility: "public", detail: "Member of the campus chapter." },
];

export const recommendations: Recommendation[] = [
  {
    name: "David Beyerlein",
    role: "Development Professional",
    relationship: "Managed Sonia directly at the Ugandan Water Project",
    date: "Nov 2025",
    quote: "She is hard-working, reliable, and self-motivated; striking a great balance between taking initiative and asking thoughtful, clarifying questions when needed. One standout was her outreach initiative to prospective partner organizations. Sonia led the effort with confidence.",
    experienceId: "uwp",
    source: { label: "LinkedIn", href: "https://www.linkedin.com/in/irakoze-sonia/details/recommendations/" },
    visibility: "public",
  },
  {
    name: "Tanner Hoffman",
    role: "Director of Program & Operations, Ugandan Water Project",
    relationship: "Worked with Sonia on a different team",
    date: "Sep 2025",
    quote: "Sonia approached every challenge from researching and engaging new corporate partners to managing communications for our golf tournament with energy and purpose. Her work was consistently thorough, high-quality, and impactful.",
    experienceId: "uwp",
    source: { label: "LinkedIn", href: "https://www.linkedin.com/in/irakoze-sonia/details/recommendations/" },
    visibility: "public",
  },
  {
    name: "Kyle Taylor",
    role: "Director of Development, Ugandan Water Project",
    relationship: "Senior colleague at the Ugandan Water Project",
    date: "Sep 2025",
    quote: "She made a remarkable impact in a short time. She is hardworking, detail-oriented, and resourceful.",
    experienceId: "uwp",
    source: { label: "LinkedIn", href: "https://www.linkedin.com/in/irakoze-sonia/details/recommendations/" },
    visibility: "public",
  },
  {
    name: "Kristen Totleben",
    role: "Open Publishing Librarian, UR Libraries",
    relationship: "Supervised Sonia’s 2025 editorial internship",
    date: "Aug 2025",
    quote: "Sonia’s work with UR-based publications was detail-oriented and excellent.",
    experienceId: "rcl",
    visibility: "public",
  },
];

export const publicExperience = experience.filter((e) => e.visibility === "public");
export const publicLeadership = leadership.filter((l) => l.visibility === "public");
export const recsFor = (id: string) => recommendations.filter((r) => r.visibility === "public" && r.experienceId === id);
