import type { FieldNote, Recognition } from "./types";

export const fieldNotes: FieldNote[] = [
  /* ── Conferences ── */
  {
    id: "nsbe-2026-baltimore",
    type: "conference",
    title: "NSBE 2026 Annual Convention",
    org: "National Society of Black Engineers",
    place: "Baltimore, MD",
    date: "Mar 18–22, 2026",
    sort: 2026.03,
    role: "Chapter Senator, representing the University of Rochester",
    note: "My second NSBE convention, and my first as the chapter’s elected Senator: representing the University of Rochester, meeting engineers and recruiters, and growing as a leader in that space.",
    takeaway: "A room full of people building, leading, and figuring it out is motivating in a calm way.",
    image: { src: "/images/nsbe-baltimore.jpg", alt: "Sonia at the NSBE 2026 convention in front of an NSBE backdrop" },
    links: [{ label: "LinkedIn reflection", href: "https://www.linkedin.com/feed/update/urn:li:activity:7441981882608734208/" }],
    visibility: "public",
    needs: ["Badge or program photo", "Specific recruiting or networking outcomes"],
  },
  {
    id: "nsbe-frc-2025",
    type: "conference",
    title: "NSBE Region 1 Fall Regional Conference",
    org: "National Society of Black Engineers",
    place: "Albany, NY",
    date: "Nov 2025",
    sort: 2025.11,
    role: "Chapter Senator",
    note: "Represented the University of Rochester chapter at the regional conference: workshops, networking, and the regional side of NSBE that I later joined as Publications Chair.",
    image: { src: "/images/nsbe-albany.jpg", alt: "Sonia smiling in a blazer at the NSBE Fall Regional Conference in Albany" },
    links: [{ label: "LinkedIn post", href: "https://www.linkedin.com/feed/update/urn:li:activity:7394510843100442624/" }],
    visibility: "public",
  },
  {
    id: "nsbe-2025-chicago",
    type: "conference",
    title: "NSBE 2025 Annual Convention (NSBE’s 50th anniversary)",
    org: "National Society of Black Engineers",
    place: "Chicago, IL",
    date: "Mar 5–9, 2025",
    sort: 2025.03,
    role: "Chapter member, first convention",
    note: "My first NSBE convention, during NSBE’s 50th anniversary. I arrived unsure which direction to take in engineering. Meeting other Rwandan engineers, including a fellow Gashora Girls Academy alumna working as a product manager, gave me clarity about my major and path.",
    takeaway: "The path you can see someone else walking is easier to choose.",
    image: { src: "/images/nsbe-chicago-2025.jpg", alt: "Sonia and a friend in front of the NSBE 50th anniversary backdrop in Chicago" },
    links: [{ label: "LinkedIn reflection", href: "https://www.linkedin.com/feed/update/urn:li:activity:7311955307604197376/" }],
    visibility: "public",
    needs: ["Sessions or companies that mattered"],
  },
  {
    id: "worlddenver-2026",
    type: "conference",
    title: "International Career Connections panel",
    org: "WorldDenver",
    place: "Denver, CO",
    date: "May 2026",
    sort: 2026.05,
    role: "Attendee",
    note: "A panel on international careers spanning aerospace, diplomacy, Fulbright, and community development. As an international student still mapping my own path, the main lesson was that there isn’t one blueprint.",
    image: { src: "/images/worlddenver-panel.jpg", alt: "Panelists speaking to an audience at the WorldDenver International Career Connections event" },
    links: [{ label: "LinkedIn reflection", href: "https://www.linkedin.com/feed/update/urn:li:activity:7476393666383740930/" }],
    visibility: "public",
  },

  /* ── Speaking ── */
  {
    id: "saquasolve-workshops",
    type: "speaking",
    title: "SAquaSolve WASH & community workshops",
    org: "SAquaSolve Rwanda, hosted by Gashora Girls Academy",
    place: "Gashora, Rwanda",
    date: "Aug 20–21, 2026",
    sort: 2026.08,
    role: "Founder; workshop team",
    note: "Two days with 53 people from Gashora Sector on safe drinking water, waterborne disease, storage, sanitation, and what young people can do. Half the point was listening.",
    image: { src: "/images/sq-ws-presenting.jpg", alt: "SAquaSolve team member presenting at the workshop" },
    links: [{ label: "Case study", href: "/work/saquasolve-rwanda" }],
    visibility: "public",
  },
  {
    id: "unibooth-pitches",
    type: "speaking",
    title: "UniBooth pitches",
    org: "Barbara J. Burger iZone, UR Libraries · Forbes Pitch Competition",
    place: "Rochester, NY",
    date: "2026",
    sort: 2026.02,
    role: "Co-founder, pitching team",
    note: "Pitched UniBooth at iZone Pitch Night, where it won a Make It Happen grant (13 winners from 28 applicants), and at the Forbes Pitch Competition.",
    links: [{ label: "Project", href: "/work/unibooth" }],
    visibility: "public",
    needs: ["Pitch photos", "Forbes Pitch Competition date and result"],
  },
  {
    id: "techgirls-info-session",
    type: "speaking",
    title: "Sunday TechDay: TechGirls info session",
    org: "Gashora Girls Academy of Science and Technology",
    place: "Gashora, Rwanda",
    date: "Oct 1, 2023",
    sort: 2023.10,
    role: "Speaker",
    note: "Two months after my own exchange, I came back to my school to walk younger students through TechGirls: what it is, how to apply, and what three weeks in the U.S. taught me.",
    image: { src: "/images/techgirls-info-session.jpg", alt: "Sonia speaking to a room of students in a classroom" },
    links: [{ label: "LinkedIn post", href: "https://www.linkedin.com/feed/update/urn:li:activity:7114625773486919681/" }],
    visibility: "public",
  },
  { id: "nsbe-panel", type: "speaking", title: "[VERIFY] NSBE internship/career panel", org: "NSBE", place: "[VERIFY]", date: "[VERIFY]", sort: 2026, role: "Panelist", note: "[VERIFY topic and audience]", visibility: "hidden", needs: ["Event name, date, topic, photo"] },
  { id: "she-will-rise", type: "speaking", title: "[VERIFY] She Will Rise: A Future Realized", org: "[VERIFY]", place: "[VERIFY]", date: "[VERIFY]", sort: 2026, role: "[VERIFY]", note: "[VERIFY]", visibility: "hidden", needs: ["Organizer, date, your role, topic, photo/video"] },

  /* ── Programs & fellowships ── */
  {
    id: "techgirls-2023",
    type: "program",
    title: "TechGirls 2023",
    org: "U.S. Department of State · Legacy International",
    place: "Virginia Tech · Denver · Washington, DC",
    date: "Jul 7 – Aug 1, 2023",
    sort: 2023.07,
    role: "Exchange participant (one of 125 girls selected internationally)",
    note: "40 hours of STEM instruction in Virginia Tech’s RIVERS course (flume experiments, my first Python), 30 hours of leadership training, a two-day job shadow at the Colorado Department of Transportation, and visits to NASA Goddard and Washington, DC.",
    takeaway: "The CDOT job shadow is the reason I applied to CDOT three years later. The program’s second phase was my Community Action Project at home: water workshops that reached 300+ residents.",
    image: { src: "/images/techgirls-cohort.jpg", alt: "TechGirls 2023 participants holding the flags of their countries" },
    links: [{ label: "Flume project", href: "/work/virginia-tech-flume" }, { label: "Community Action Project", href: "/work/techgirls-community-action-project" }],
    visibility: "public",
  },
  { id: "kearns", type: "program", title: "Kearns Scholars Program", org: "David T. Kearns Center, University of Rochester", place: "Rochester, NY", date: "2025 – now", sort: 2025.05, role: "Kearns Scholar", note: "Joined after completing Navigating the Academy (CASC 145). The Kearns Center supports first-generation and low-income students with advising through college, career, and life.", visibility: "public" },
  { id: "schwartz", type: "program", title: "Schwartz Community-Based Internship Program", org: "Greene Center, University of Rochester", place: "Rochester, NY", date: "Summer 2025", sort: 2025.06, role: "Schwartz Scholar", note: "Competitive funded placement with a Rochester-area nonprofit; mine was the Ugandan Water Project.", visibility: "public" },
  { id: "colorstack", type: "program", title: "ColorStack", org: "ColorStack", place: "Remote", date: "2025 – now", sort: 2025.01, role: "Student Fellow", note: "A community promoting diversity in tech: peers, technical projects, and mentorship.", visibility: "public" },
  { id: "cpi", type: "program", title: "Career Pathways Initiative Fellows Program", org: "Career Pathways Initiative", place: "Remote", date: "2025 – now", sort: 2025.10, role: "Fellow", note: "Professional networks, career development, and mentorship for first-generation, low-income college students.", visibility: "public" },
  { id: "meliora-collective", type: "program", title: "Meliora Collective Mentorship Program", org: "University of Rochester", place: "Rochester, NY · Boston", date: "Spring 2025 – now", sort: 2025.02, role: "Mentee", note: "Matched with an alumnus mentor who helped me think through choosing my major. We later met in person in Boston, and still talk regularly.", visibility: "public" },
  { id: "sia", type: "program", title: "[VERIFY SIA PROGRAM FULL NAME]", org: "[VERIFY]", place: "[VERIFY]", date: "[VERIFY YEAR]", sort: 2024, role: "[VERIFY ROLE]", note: "[VERIFY EXPERIENCE, OUTCOME]", visibility: "hidden", needs: ["Full name, year, role, experience, outcome"] },
];

export const recognition: Recognition[] = [
  {
    id: "p4p",
    title: "Davis Projects for Peace grant",
    issuer: "Davis Projects for Peace · University of Rochester",
    year: "2026",
    sort: 2026.04,
    kind: "Grant",
    why: "US$10,000 for SAquaSolve Rwanda. I was one of two University of Rochester students funded in 2026 by this global program for student-led peacebuilding projects.",
    opened: "Funded the 2026 workshops, field assessment, and water-testing work in Gashora.",
    href: "https://www.rochester.edu/college/studentfellowships/news-events/projects-for-peace.html",
    image: { src: "/images/sq-ws-group.jpg", alt: "SAquaSolve workshop group photo" },
    visibility: "public",
  },
  {
    id: "handler",
    title: "Alan & Jane Handler Endowed Scholarship",
    issuer: "University of Rochester",
    year: "2024",
    sort: 2024.03,
    kind: "Scholarship",
    why: "The University of Rochester’s most prestigious scholarship, offered to about 1% of the incoming class after a rigorous selection process.",
    opened: "Made studying engineering in the U.S. possible.",
    visibility: "public",
  },
  {
    id: "eac-essay",
    title: "3rd Prize, East African Community Students’ Essay Writing Competition",
    issuer: "East African Community",
    year: "2022",
    sort: 2022.06,
    kind: "Award",
    why: "Represented Rwanda in a regional competition. The prize was awarded in Arusha, Tanzania, at an event with the region’s heads of state.",
    opened: "My first trip representing my country, and conversations with student winners from Kenya, Tanzania, Uganda, Burundi, and South Sudan.",
    image: { src: "/images/eac-award-1.jpg", alt: "Sonia receiving her award in Arusha" },
    visibility: "public",
  },
  {
    id: "qcec",
    title: "Silver Award, Queen’s Commonwealth Essay Competition",
    issuer: "Royal Commonwealth Society",
    year: "2023",
    sort: 2023.06,
    kind: "Award",
    why: "Awarded on the recommendation of the Royal Commonwealth Society’s judging panels.",
    image: { src: "/images/cert-qcec-2023.jpg", alt: "Queen’s Commonwealth Essay Competition 2023 Silver Award certificate (signatures blurred)" },
    visibility: "public",
  },
  {
    id: "izone",
    title: "iZone Make It Happen Grant",
    issuer: "Barbara J. Burger iZone, UR Libraries",
    year: "2026",
    sort: 2026.02,
    kind: "Grant",
    why: "Seed funding for UniBooth; one of 13 winners from 28 applicants.",
    opened: "Gave the UniBooth team a budget for the next step and a reason to write a real pilot proposal.",
    visibility: "public",
  },
  { id: "greene", title: "Greene Center Summer Internship Funding", issuer: "University of Rochester", year: "2026", sort: 2026.01, kind: "Funding", why: "Competitive funding, made possible by alumni gifts, that supported my CDOT internship.", visibility: "public" },
  { id: "deans-list", title: "Dean’s List", issuer: "University of Rochester", year: "Fall 2024", sort: 2024.12, kind: "Honor", why: "First semester at Rochester.", visibility: "public" },
];

export const publicFieldNotes = fieldNotes.filter((f) => f.visibility === "public");
export const publicRecognition = recognition.filter((r) => r.visibility === "public");
