import type { Project } from "./types";

const P4P_URL = "https://www.rochester.edu/college/studentfellowships/news-events/projects-for-peace.html";
const COMPASS_CARD = "https://docs.google.com/presentation/d/12Ta0FAas_kKpvBQ0F2O1W6uQZGFcWMgNj-wkbhd-SQ0/";

export const projects: Project[] = [
  /* ───────────────────────── FLAGSHIP ───────────────────────── */
  {
    slug: "saquasolve-rwanda",
    title: "SAquaSolve Rwanda",
    tagline: "Turning a lake people already use into water they can safely drink.",
    year: "2023 – now",
    sort: 2026.08,
    tier: "flagship",
    visibility: "public",
    role: "Founder & Legal Representative",
    team: "With Nadine Uwizeyimana (technical lead, water and sanitation engineer) and a workshop team in Gashora",
    status: "in-development",
    statusLabel: "Phase 1 done · system not built",
    categories: ["Water", "Infrastructure", "Mechanical"],
    tools: ["Systems design", "Solar pumping", "Water treatment", "Field assessment", "Community engagement", "Grant writing"],
    cover: { src: "/images/sq-ws-hall-wide.jpg", alt: "A full community hall at Gashora Girls Academy during the SAquaSolve WASH workshops" },
    links: [
      { label: "saquasolverwanda.org", href: "https://www.saquasolverwanda.org" },
      { label: "Projects for Peace announcement", href: P4P_URL },
    ],
    challenge: "Designing a water system before knowing what’s in the water.",
    summary:
      "Lake Mirayi sits beside communities in Gashora, but its water is untreated. In 2026, a $10,000 Projects for Peace grant funded phase one: community workshops, field assessment, and water testing that will decide the design. The system itself hasn’t been built.",
    story: [
      {
        type: "stats",
        stats: [
          { value: "$10,000", label: "Davis Projects for Peace grant", note: "Funds phase one, not construction" },
          { value: "53", label: "people from Gashora Sector at the workshops" },
          { value: "4", label: "student Youth Ambassadors selected" },
          { value: "7", label: "engineering decision gates before construction" },
        ],
      },
      {
        type: "text",
        title: "The problem",
        body: [
          "Bugesera District has nine lakes and three rivers. Lake Mirayi sits right beside the communities of Gashora Sector, and many residents collect from it despite parasites, bacteria, and the risk of crocodiles.",
          "Having water nearby isn’t the same as having safe water. District survey data cited in our technical report show that 20.9% of Bugesera households don’t use the drinking-water source closest to them, and 65.7% of those say it doesn’t work properly.",
          "I spent three years as a boarding student at Gashora Girls Academy, so this isn’t an abstract site for me. It’s why SAquaSolve started here.",
        ],
      },
      {
        type: "steps",
        title: "From proposal to evidence",
        intro: "2026 was about replacing assumptions with information before anyone spends money on hardware.",
        steps: [
          { label: "Spring 2026", title: "Proposal and grant", body: "Wrote the Projects for Peace proposal for solar-powered water filtration on Lake Mirayi and won the University of Rochester’s 2026 grant." },
          { label: "July 2026", title: "Technical review", body: "Led a 32-page technical concept and pre-feasibility report, and took the concept to an informal listening session with practicing hydraulic, water-quality, and environmental engineers." },
          { label: "August 2026", title: "Field assessment", body: "Our team made field visits and initial assessments around Lake Mirayi, the candidate source, to understand the site, local water conditions, and community needs." },
          { label: "20–21 Aug 2026", title: "Two days of WASH workshops", body: "Hosted by Gashora Girls Academy. 53 people from Gashora Sector covered safe drinking water, waterborne disease, safe storage, sanitation, and environmental protection, and told us about their own water challenges." },
          { label: "August 2026", title: "Youth Ambassadors", body: "Selected four Gashora Girls Academy students to keep water, sanitation, and hygiene awareness going after we left." },
          { label: "Ongoing", title: "Water-quality testing", body: "Coordinating laboratory testing of Lake Mirayi with the Rwanda Institute for Conservation Agriculture (RICA). The results will set the treatment design." },
        ],
      },
      {
        type: "compare",
        title: "The engineering pivot",
        intro: "My proposal pictured a pumping station feeding a single kiosk. The technical review changed the shape of the system: solar power drives the lift, storage is sized properly, and one treatment hub feeds several community access points, which is easier to monitor and maintain than standalone kiosks.",
        before: { src: "/images/sq-concept-early.jpg", alt: "Early concept sketch: intake pumping station, pipeline, containerized treatment plant, tank, and one water kiosk", label: "Early concept · single kiosk" },
        after: { src: "/images/sq-concept-current.jpg", alt: "Current preliminary concept: solar-powered intake, raw-water pipeline, containerized treatment, treated-water storage, and distribution to several access points", label: "Current concept · one hub, many access points" },
      },
      {
        type: "architecture",
        title: "The reference system",
        intro: "The goal is a complete service from source to tap, not a standalone treatment device. Every component exists as proven, commercially available equipment, so the engineering work is careful selection and integration for this site.",
        parts: [
          { label: "Intake", detail: "Screened lake intake at a location set by the field assessment" },
          { label: "Lift", detail: "A single solar-powered lift to the head of a gravity treatment train" },
          { label: "Treatment", detail: "Multiple barriers ending in disinfection; process chosen from lab results" },
          { label: "Storage", detail: "Protected tank sized by mass balance" },
          { label: "Dispensing", detail: "Hygienic multi-tap access points" },
          { label: "Operation", detail: "Trained local operator with continuous water-quality monitoring" },
        ],
        caption: "Preliminary concept, not an engineering drawing. Final treatment, sizing, and routing depend on testing, site assessment, and approvals.",
      },
      {
        type: "list",
        title: "Constraints we found",
        items: [
          "The grant funds community and engineering work, not construction.",
          "The source water hasn’t been characterized yet, so treatment can’t be chosen responsibly.",
          "The engineers at the listening session pushed on abstraction rights, competing water uses, permitting, affordability, and realistic demand. Each one is now a question in the field program.",
          "The site is off-grid, so pumping and treatment need solar power.",
          "District and regulatory approvals are required before anything is built.",
          "I’m a full-time student in Rochester, so the work depends on strong partners on the ground.",
        ],
      },
      {
        type: "status",
        title: "Where it stands (October 2026)",
        rows: [
          { state: "done", text: "Two days of WASH workshops with 53 participants, hosted by Gashora Girls Academy" },
          { state: "done", text: "Four Youth Ambassadors selected" },
          { state: "done", text: "Initial field assessment of the project area and Lake Mirayi" },
          { state: "done", text: "Preliminary system concept and technical report (v1.1)" },
          { state: "underway", text: "Lake Mirayi water-quality testing with RICA" },
          { state: "next", text: "Engineering design, approvals with local authorities, and resource mobilization" },
          { state: "not-started", text: "Construction and operation" },
        ],
      },
      {
        type: "steps",
        title: "2026–27 plan",
        intro: "Six workstreams from our annual action plan. This is a plan with a planned budget of $145,000. That funding isn’t secured.",
        steps: [
          { label: "Testing", title: "Water quality & community assessment", body: "Four rounds of lake sampling, lab testing, and seasonal monitoring." },
          { label: "Engineering", title: "Infrastructure & engineering development", body: "Hydraulic and intake design, treatment selection, solar and pumping design, storage and distribution, site planning, supplier quotes." },
          { label: "Education", title: "Community WASH education", body: "Eight workshops and consultation sessions." },
          { label: "Youth", title: "Youth water leadership", body: "Youth Ambassador activities and school-based water education." },
          { label: "Partners", title: "Partnerships & resources", body: "Engagement with government, the water sector, technical partners, and funders." },
          { label: "Readiness", title: "Equipment & pilot readiness", body: "Procurement planning for intake, treatment, solar, storage, and distribution." },
        ],
      },
      {
        type: "gallery",
        title: "From the workshops",
        images: [
          { src: "/images/sq-ws-group.jpg", alt: "Workshop participants and the SAquaSolve team gathered for a group photo at Gashora Girls Academy", caption: "Participants and team, Gashora Girls Academy, August 2026" },
          { src: "/images/sq-ws-presenting.jpg", alt: "A SAquaSolve team member presenting beside the project banner", caption: "Presenting the project" },
          { src: "/images/sq-ws-activity.jpg", alt: "Participants standing and raising their hands during an interactive activity", caption: "Interactive session" },
          { src: "/images/sq-ws-listening.jpg", alt: "A team member speaking with seated participants", caption: "Listening to residents" },
          { src: "/images/sq-ws-team-prep.jpg", alt: "SAquaSolve team members preparing in the hall before the workshop", caption: "Setting up" },
          { src: "/images/sq-lake-mirayi.jpg", alt: "Lake Mirayi with reeds in the foreground", caption: "Lake Mirayi, the candidate source" },
        ],
      },
      {
        type: "quote",
        quote: "Peace cannot exist where people still struggle for what is a basic human right — water.",
        cite: "Sonia, on being named a 2026 Projects for Peace grantee",
      },
      {
        type: "lesson",
        title: "What I learned",
        body: "Designing in the right order matters more than designing fast. Every time I tried to pick a treatment technology early, the honest answer was “it depends on the water.” Building decision gates into the plan made it slower and much easier to defend to engineers, funders, and the district.",
      },
    ],
    artifacts: [
      { kind: "diagram", label: "Preliminary system concept", src: "/images/sq-concept-current.jpg", href: "/images/sq-concept-current.jpg" },
      { kind: "diagram", label: "Early concept (before the pivot)", src: "/images/sq-concept-early.jpg", href: "/images/sq-concept-early.jpg" },
      { kind: "photo", label: "Workshop group photo", src: "/images/sq-ws-group.jpg", href: "/images/sq-ws-group.jpg" },
      { kind: "demo", label: "saquasolverwanda.org (which I built)", href: "https://www.saquasolverwanda.org" },
      { kind: "article", label: "University of Rochester grant announcement", href: P4P_URL },
      { kind: "report", label: "Technical concept & pre-feasibility report v1.1", note: "32 pages; available on request" },
    ],
    related: { projects: ["saquasolve-website"], experience: ["uwp"] },
    needs: [
      "Lake Mirayi field photos taken by Sonia (current lake photo is by Nadine Uwizeyimana)",
      "Water-quality results from RICA when released",
      "Service-area map",
      "Short workshop video (five clips exist in Media/; need review and consent check)",
      "Which photos show Sonia (for captions)",
      "What would you do differently? (case-study question 11)",
    ],
  },
  {
    slug: "cdot-bridge-asset-management",
    title: "Bridge asset data at CDOT",
    tagline: "Making a statewide bridge inventory match what’s actually in the field.",
    year: "Summer 2026",
    sort: 2026.07,
    tier: "flagship",
    visibility: "public",
    role: "Engineering Intern, Bridge Asset Management (Staff Bridge Branch)",
    status: "completed",
    statusLabel: "Completed · summer 2026",
    categories: ["Infrastructure", "Data & AI", "Mechanical"],
    tools: ["SQL Server (SSMS)", "SNBI", "Plan-set review", "SIMSA", "OnBase", "OTIS", "OpenRoads Designer"],
    cover: { src: "/images/cdot-field-site.jpg", alt: "Sonia in a hard hat and high-visibility vest at a Colorado highway construction site" },
    links: [{ label: "CDOT Bridges & Structures", href: "https://www.codot.gov/programs/bridge" }],
    challenge: "Records spread across three systems that don’t always agree.",
    summary:
      "SQL against inspection and clearance databases, treatment identification across 16 projects, cross-checks between record systems, and time in the field with bridge inspectors. Three years after a two-day job shadow in the same office.",
    story: [
      {
        type: "stats",
        stats: [
          { value: "3,500+", label: "bridges in the statewide inventory the team manages" },
          { value: "16", label: "projects reviewed for bridge treatment identification" },
          { value: "3", label: "record systems cross-checked (SIMSA, OnBase, OTIS)" },
        ],
      },
      {
        type: "text",
        title: "The problem",
        body: [
          "Colorado’s bridge asset decisions depend on accurate inventory, inspection, and clearance data, kept to federal asset-management rules (23 CFR Part 515) and the Specifications for the National Bridge Inventory (SNBI).",
          "That information lives in several systems, and structure identifiers don’t always match between them. A record that disagrees with the field is a real problem, not a typo.",
        ],
      },
      {
        type: "steps",
        title: "What I did",
        steps: [
          { label: "Data", title: "SQL on bridge databases", body: "Wrote and ran SQL queries in SQL Server Management Studio against structural inspection, project, and vertical-clearance databases for analysis and reporting." },
          { label: "Plans", title: "Bridge treatment identification", body: "Reviewed bridge drawings and structural plan sets for 16 projects, identified each structure, and recorded the treatment planned for it, such as bridge-rail or guardrail replacement, updating records to SNBI." },
          { label: "Records", title: "Cross-checking systems", body: "Cross-referenced structure identifiers across SIMSA, OnBase, and OTIS to find and fix discrepancies." },
          { label: "Field", title: "Inspections and clearances", body: "Joined licensed bridge inspectors in the field, traveled with intern teams to record vertical-clearance measurements, and watched girder erection on the I-70 Floyd Hill project." },
          { label: "Tools", title: "Drawings", body: "Started learning OpenRoads Designer for engineering drawings." },
        ],
      },
      {
        type: "text",
        title: "How I got here",
        body: [
          "In July 2023, as a 17-year-old TechGirls participant, I spent two days in this office on a job shadow hosted by the same team. I remember quietly wishing I could come back. In May 2026 I did, with Greene Center internship funding from the University of Rochester.",
        ],
      },
      {
        type: "quote",
        quote: "From the drawings and inspections to the data, construction crews, and engineers, they’re all different pieces of the same puzzle.",
        cite: "Sonia, one month into the internship",
      },
      {
        type: "gallery",
        title: "Field and office",
        images: [
          { src: "/images/cdot-field-site.jpg", alt: "Sonia in PPE at a mountain highway construction site", caption: "Field visit, summer 2026" },
          { src: "/images/cdot-welcome-colorado.jpg", alt: "Sonia beside a Welcome to Colorful Colorado sign at CDOT", caption: "CDOT headquarters, Denver" },
          { src: "/images/cdot-announcement.jpg", alt: "Graphic announcing Sonia joining CDOT as an engineering intern, summer 2026", caption: "The offer, April 2026" },
        ],
      },
      {
        type: "lesson",
        title: "What I learned",
        body: "Infrastructure is as much an information system as a physical one. Inspectors, plan sets, databases, and crews all describe the same bridge, and my most useful work was making those descriptions agree.",
      },
    ],
    artifacts: [
      { kind: "photo", label: "Field visit", src: "/images/cdot-field-site.jpg", href: "/images/cdot-field-site.jpg" },
      { kind: "post", label: "One month at CDOT (LinkedIn)", href: "https://www.linkedin.com/feed/update/urn:li:activity:7476382134052470784/" },
    ],
    related: { projects: ["cdot-compass"], experience: ["cdot"] },
    needs: [
      "Region 2 VRI/AR workflow: what it is and what you did (kept off the site until explained)",
      "Any CDOT-approved visuals of your work (no internal data)",
      "Recommendation from a CDOT supervisor",
      "Confirm internship end date",
    ],
  },
  {
    slug: "cdot-compass",
    title: "CDOT Compass",
    tagline: "A map of a large state agency, built by its newest intern.",
    year: "2026",
    sort: 2026.07,
    tier: "flagship",
    visibility: "public",
    role: "Idea, design, and development",
    status: "completed",
    statusLabel: "Live prototype · published by CDOT",
    categories: ["Software", "Design", "Infrastructure"],
    tools: ["React 19", "TypeScript", "Vite", "Tailwind CSS", "Framer Motion", "React Router 7", "Vercel", "Claude"],
    cover: { src: "/images/compass-dashboard.jpg", alt: "CDOT Compass dashboard with quick actions for exploring divisions, projects, and mentors" },
    links: [
      { label: "Live demo", href: "https://cdot-compass.vercel.app" },
      { label: "GitHub", href: "https://github.com/irakozesonia123-bot/cdot-compass" },
      { label: "CDOT idea card", href: COMPASS_CARD },
    ],
    challenge: "Turning an org chart into something a first-week intern can navigate.",
    summary:
      "A web prototype that helps new staff explore CDOT’s divisions, projects, people, and career paths. CDOT’s Process Improvement office published it as a 2026 Lean Everyday Idea.",
    story: [
      {
        type: "text",
        title: "The problem",
        body: [
          "CDOT is a big organization. In my first weeks I kept asking what each division actually does, what projects are underway, and who to talk to. The information existed, but it was scattered.",
        ],
      },
      {
        type: "steps",
        title: "What I built",
        steps: [
          { label: "01", title: "A dashboard for first-week questions", body: "Explore divisions, browse projects, find a mentor, and see upcoming events from one screen." },
          { label: "02", title: "Compass Guide", body: "Asks a few questions and suggests divisions, projects, and people to look at." },
          { label: "03", title: "Global search", body: "One search box across divisions, projects, and people." },
          { label: "04", title: "Feedback loop", body: "I tested ideas with colleagues and changed the prototype as I learned what new staff actually needed." },
        ],
      },
      {
        type: "architecture",
        title: "How it’s built",
        parts: [
          { label: "Frontend", detail: "React 19 and TypeScript on Vite" },
          { label: "UI", detail: "Tailwind CSS and Framer Motion" },
          { label: "Routing", detail: "React Router 7" },
          { label: "Data", detail: "Local JSON content, no backend or internal systems access" },
          { label: "Hosting", detail: "Vercel" },
          { label: "Process", detail: "AI-assisted coding with Claude" },
        ],
      },
      {
        type: "gallery",
        title: "Screens",
        images: [
          { src: "/images/compass-dashboard.jpg", alt: "Compass dashboard", caption: "Dashboard" },
          { src: "/images/compass-explore.jpg", alt: "Explore Divisions grid with filters", caption: "Explore divisions" },
          { src: "/images/compass-guide.jpg", alt: "Compass Guide onboarding screen", caption: "Compass Guide" },
          { src: "/images/compass-search.jpg", alt: "Global search overlay", caption: "Global search" },
        ],
      },
      {
        type: "status",
        title: "Outcome",
        rows: [
          { state: "done", text: "Published by CDOT’s Process Improvement office on 2 July 2026 as a Lean Everyday Idea (#BorrowThis)" },
          { state: "done", text: "Entered in the 2026 CDOT Innovation Challenge" },
          { state: "done", text: "Live as a public prototype; it is not an official CDOT system" },
        ],
      },
      {
        type: "quote",
        quote: "Innovation doesn’t always require solving the biggest problem in the room. Sometimes it starts by noticing everyday friction, listening to people, and asking, ‘How can we make this better?’",
        cite: "Sonia, July 2026",
      },
    ],
    artifacts: [
      { kind: "demo", label: "Live prototype", href: "https://cdot-compass.vercel.app" },
      { kind: "code", label: "Source on GitHub", href: "https://github.com/irakozesonia123-bot/cdot-compass" },
      { kind: "publication", label: "CDOT Lean Everyday Ideas card", src: "/images/cdot-compass-idea-card.jpg", href: COMPASS_CARD },
      { kind: "post", label: "CDOT Process Improvement director’s post", href: "https://www.linkedin.com/feed/update/urn:li:activity:7483587378729820160/" },
    ],
    related: { projects: ["cdot-bridge-asset-management"], experience: ["cdot"] },
    needs: ["Innovation Challenge result, if announced", "Presentation slides or video if you presented it", "What would you do differently?"],
  },
  {
    slug: "cropsight-knowledge-base",
    title: "CropSight knowledge base",
    tagline: "Clean, traceable reference data for an AI that diagnoses crop disease.",
    year: "2026 – now",
    sort: 2026.01,
    tier: "flagship",
    visibility: "public",
    role: "Data Research Intern, AGR Sensors",
    team: "Multi-contributor data team",
    status: "ongoing",
    statusLabel: "Ongoing",
    categories: ["Data & AI", "Software"],
    tools: ["Python", "JSON Schema", "Git", "rclone"],
    links: [],
    challenge: "Many people editing one dataset that a model will trust.",
    summary:
      "Auditing and structuring the reference data behind CropSight, AGR Sensors’ AI crop-disease diagnosis system: 22 reference books, 250+ chunks, 212 entries, zero schema errors.",
    story: [
      {
        type: "stats",
        stats: [
          { value: "22", label: "agricultural reference books" },
          { value: "250+", label: "document chunks audited" },
          { value: "212", label: "disease & pest entries catalogued" },
          { value: "0", label: "schema validation errors" },
        ],
      },
      { type: "text", title: "The problem", body: ["A diagnosis model is only as trustworthy as its reference data. CropSight’s knowledge comes from agricultural reference books that have to be split, checked, and structured before any model can use them."] },
      {
        type: "list",
        title: "What I do",
        items: [
          "Audited document chunks against their source books until every page was covered.",
          "Converted 212 disease and pest entries to ML-ready JSON.",
          "Wrote Python checks for schema, page ranges, image counts, and scientific names.",
          "Kept a multi-contributor Git repository in sync (branching, rebasing, conflict resolution) and synced 600 MB+ of source PDFs with rclone.",
        ],
      },
      { type: "lesson", title: "What I learned", body: "Data quality is mostly careful, repeatable checking. Small validation scripts beat reading every record by eye, and they keep working when the dataset grows." },
    ],
    artifacts: [],
    related: { experience: ["agr"] },
    needs: ["Any shareable, non-proprietary artifact (e.g. a redacted schema or validation output)"],
  },

  /* ───────────────────────── SUPPORTING ───────────────────────── */
  {
    slug: "saquasolve-website",
    title: "saquasolverwanda.org",
    tagline: "A full organization website: pages, blog CMS, contact, newsletter, and donations.",
    year: "2026",
    sort: 2026.06,
    tier: "supporting",
    visibility: "public",
    role: "Design and development",
    status: "completed",
    statusLabel: "Live",
    categories: ["Software", "Design", "Water"],
    tools: ["Next.js 16", "React 19", "TypeScript", "Tailwind CSS", "Sanity", "Resend", "Stripe", "Vercel"],
    cover: { src: "/images/saquasolve-site-about.jpg", alt: "SAquaSolve Rwanda website About page" },
    links: [{ label: "Live site", href: "https://www.saquasolverwanda.org" }],
    challenge: "Explaining infrastructure that isn’t built yet, honestly.",
    summary: "I designed and built SAquaSolve’s website in Next.js with a Sanity blog, Resend email, and Stripe donations. 89 commits in a private repository.",
    story: [
      { type: "text", title: "Why", body: ["SAquaSolve needed a credible home for partners, funders, and residents that explains an unfinished project without overstating it, and lets people get in touch or give."] },
      {
        type: "architecture",
        title: "How it’s built",
        parts: [
          { label: "Framework", detail: "Next.js 16 App Router, React 19, TypeScript" },
          { label: "Content", detail: "Sanity CMS for the blog; typed site data for pages" },
          { label: "Email", detail: "Resend for contact and newsletter" },
          { label: "Payments", detail: "Stripe for donations" },
          { label: "Pages", detail: "Overview, our work, what we do, about, impact, FAQ, partner, donate, media, legal" },
        ],
      },
      { type: "gallery", title: "Pages", images: [
        { src: "/images/saquasolve-site-about.jpg", alt: "About page", caption: "About" },
        { src: "/images/saquasolve-site-programs.jpg", alt: "What We Do page", caption: "Program areas" },
      ] },
      { type: "lesson", title: "What I learned", body: "A website for a real organization is mostly content decisions. The code was the easier part." },
    ],
    artifacts: [{ kind: "demo", label: "Live site", href: "https://www.saquasolverwanda.org" }],
    related: { projects: ["saquasolve-rwanda"] },
  },
  {
    slug: "techgirls-community-action-project",
    title: "TechGirls Community Action Project",
    tagline: "Water-conservation and hygiene workshops for my community, after my TechGirls exchange.",
    year: "2023",
    sort: 2023.09,
    tier: "supporting",
    visibility: "public",
    role: "Project lead",
    team: "TechGirls 2023, Phase 2: community-based project in my home country",
    status: "completed",
    statusLabel: "Completed · certificate issued Feb 2024",
    categories: ["Water"],
    tools: ["Workshop design", "Public teaching", "Community outreach"],
    links: [],
    challenge: "Teaching water safety with no budget and no equipment.",
    learned: "Awareness matters, but it doesn’t make lake water safe to drink.",
    summary:
      "Every TechGirls participant comes home with a community project. Mine was a series of education workshops in my community near Lake Mirayi on water conservation, stopping pollution of shared water, and safe handling and hygiene. They reached 300+ residents.",
    story: [
      { type: "stats", stats: [{ value: "300+", label: "residents reached" }, { value: "2023", label: "after the TechGirls exchange" }] },
      { type: "text", title: "Why education", body: [
        "After TechGirls, every participant runs a community action project at home. I was a secondary school student with no money and no equipment, and teaching was the one thing I could actually give.",
        "The workshops covered water conservation, stopping pollution of the water we all share, and safe handling and hygiene.",
      ] },
      { type: "lesson", title: "What it taught me", body: "It was real work and it mattered, and I also knew it wasn’t enough. Awareness doesn’t make lake water safe to drink. That gap is what pushed me toward engineering an actual water system." },
    ],
    artifacts: [{ kind: "certificate", label: "2023 Community Action Project certificate (TechGirls)", note: "Issued Feb 2024; on LinkedIn" }],
    related: { projects: ["saquasolve-rwanda", "virginia-tech-flume"] },
    needs: [
      "Workshop photos from 2023",
      "Exact location(s) and dates of the workshops",
      "How the 300+ was counted (attendance across sessions?)",
      "Copy of the Community Action Project certificate image",
      "Confirm whether the $500 funding and weekly school workshops (Oct 2025 resume) belong to this project or to later AquaSolve work",
    ],
  },
  {
    slug: "cubesat-structures",
    title: "UR CubeSat structures",
    tagline: "A satellite frame that has to be light and survive a launch.",
    year: "2025 – now",
    sort: 2025.04,
    tier: "supporting",
    visibility: "public",
    role: "Structures Team Member",
    team: "University of Rochester CubeSat (student team)",
    status: "ongoing",
    statusLabel: "Ongoing",
    categories: ["Aerospace", "Mechanical"],
    tools: ["Siemens NX", "MATLAB", "Vibration analysis", "Thermal analysis"],
    links: [],
    challenge: "Mass limits on one side, launch vibration on the other.",
    summary: "Modeling the CubeSat’s structural frame in Siemens NX and running vibration and thermal simulations, while working out fit and integration with the avionics and propulsion sub-teams.",
    story: [
      { type: "text", title: "The challenge", body: ["A CubeSat has to stay inside tight mass limits and still survive launch vibration and thermal cycling, with every subsystem fitting inside a small, standard frame."] },
      { type: "list", title: "What I do", items: [
        "Model the structural frame in Siemens NX.",
        "Run vibration and thermal simulations in MATLAB to check the structure against launch conditions.",
        "Work through fit and integration questions with the avionics and propulsion sub-teams.",
      ] },
    ],
    artifacts: [],
    needs: ["CAD screenshots of the frame", "FEA / vibration or thermal plots", "Team or prototype photo", "Lessons learned", "Your specific part of the frame"],
  },
  {
    slug: "aero-design-glider",
    title: "Yellowjackets Aero Design",
    tagline: "Iterating a competition aircraft until it’s lighter and still stable.",
    year: "2025 – now",
    sort: 2025.08,
    tier: "supporting",
    visibility: "public",
    role: "Design Lead (also social media)",
    team: "University of Rochester Yellowjackets Aero Design, SAE Aero Design",
    status: "ongoing",
    statusLabel: "Ongoing",
    categories: ["Aerospace", "Mechanical"],
    tools: ["Siemens NX", "FEA", "Laser cutting", "Prototyping"],
    links: [],
    challenge: "Cutting weight without losing stiffness or stability.",
    summary: "Modeling wing, tail, and fuselage structures in Siemens NX, comparing configurations with FEA, and building laser-cut prototypes across 15+ iterations. The team cut airframe weight by about 10%.",
    story: [
      { type: "stats", stats: [{ value: "15+", label: "design iterations" }, { value: "~10%", label: "airframe weight reduction (team result)" }] },
      { type: "list", title: "What I do", items: [
        "Model wing, tail, and fuselage structures in Siemens NX.",
        "Use FEA to compare wing and tail configurations for stress and stability.",
        "Build and test laser-cut prototypes.",
      ] },
    ],
    artifacts: [],
    needs: ["Confirm aircraft/glider name (e.g. “Sirocco”) and competition year", "CAD screenshots", "Prototype or flight photos", "Calculations or design review slides", "Lessons learned"],
  },
  {
    slug: "unibooth",
    title: "UniBooth",
    tagline: "A Korean-style photo booth to give students a reason to make memories on campus.",
    year: "2025 – now",
    sort: 2026.02,
    tier: "supporting",
    visibility: "public",
    role: "Co-founder, COO & CFO",
    team: "With co-founders Nennin Toure and Hyeji Kim",
    status: "concept",
    statusLabel: "Concept · pilot proposed",
    categories: ["Entrepreneurship", "Design"],
    tools: ["Customer survey", "Business model", "Financial projections", "Pitch deck", "Partnership proposal"],
    cover: { src: "/images/unibooth-mark.jpg", alt: "UniBooth logo: a four-pointed star with a graduation tassel above the word Unibooth" },
    links: [],
    challenge: "Proving a fun idea can be a responsible library partnership.",
    summary: "A student startup for customizable, university-branded photo booths. We surveyed students, built the business model and pitch, won an iZone Make It Happen grant, and wrote a pilot proposal for Rush Rhees Library. No booth is installed yet.",
    story: [
      { type: "text", title: "The opportunity", body: [
        "Students want easy, affordable ways to capture campus life, but photo booths usually show up only at scheduled events. Our survey of University of Rochester students (45+ responses) found that over 80% of respondents felt they lacked a strong connection to campus spirit.",
        "UniBooth is a compact, self-service booth with university-themed and seasonal frames, printed strips, and an optional digital copy, priced per session.",
      ] },
      { type: "steps", title: "What we did", steps: [
        { label: "Discovery", title: "Student survey", body: "45+ responses about how students want to document campus life." },
        { label: "Model", title: "Business model", body: "Pay-per-use sessions plus rentals for organizations and events. I led operations and financial planning." },
        { label: "Funding", title: "iZone Make It Happen Grant", body: "Pitched at iZone Pitch Night and won seed funding, one of 13 winners from 28 applicants." },
        { label: "Pitch", title: "Forbes Pitch Competition", body: "Pitched UniBooth at the Forbes Pitch Competition." },
        { label: "Pilot", title: "Library pilot proposal", body: "Drafted a one-semester, low-risk pilot proposal for Rush Rhees Library covering privacy, maintenance, placement, accessibility, and what happens after the founders graduate." },
      ] },
      { type: "status", title: "Where it stands", rows: [
        { state: "done", text: "Survey, business model, pitch deck, and seed grant" },
        { state: "done", text: "Pilot partnership proposal drafted for Rush Rhees Library" },
        { state: "not-started", text: "Prototype booth and installation (subject to written approval)" },
      ] },
      { type: "lesson", title: "What I learned", body: "Institutions say yes to risk they can see clearly. Our proposal got stronger when it answered the library’s questions about privacy, upkeep, and continuity before asking for space." },
    ],
    artifacts: [],
    needs: ["Confirm “Level Up UR Memories” name and how it relates to UniBooth", "Booth mockups or renders", "Pitch photos", "Forbes Pitch Competition result", "Whether the executive summary/pitch deck can be shared"],
  },
  {
    slug: "timber-truss-bridge",
    title: "Optimized timber truss bridge",
    tagline: "A 52-meter truss, three designs, and the lightest one that still passes.",
    year: "2024",
    sort: 2024.11,
    tier: "archive",
    visibility: "public",
    role: "Student designer",
    team: "Course project, The Engineering of Bridges (ME 104)",
    status: "completed",
    statusLabel: "Coursework",
    categories: ["Mechanical", "Infrastructure", "Coursework"],
    tools: ["Dr.Frame", "Structural analysis"],
    links: [],
    challenge: "Saving weight without crossing buckling or deflection limits.",
    learned: "Every member you lighten changes the load path somewhere else.",
    summary: "Designed and analyzed three truss configurations for a 52 m timber bridge in Dr.Frame, checking buckling, compressive stress, and a displacement limit under 5 cm. The final design came out 34% lighter.",
    story: [
      { type: "stats", stats: [{ value: "52 m", label: "span" }, { value: "3", label: "truss designs compared" }, { value: "< 5 cm", label: "displacement limit" }, { value: "34%", label: "lighter final design" }] },
      { type: "list", title: "Constraints", items: ["Member buckling limits", "Compressive stress limits", "Maximum displacement under 5 cm", "Balanced load paths"] },
      { type: "text", title: "Approach", body: ["I modeled and simulated three truss designs in Dr.Frame, then iterated member sizes on the best one to minimize weight while keeping stiffness and every limit satisfied."] },
    ],
    artifacts: [],
    bench: { note: "First-year course, first real optimization problem.", sticker: "ME 104" },
    needs: ["Dr.Frame screenshots or final drawing", "Calculation sheet or report", "Baseline the 34% is measured against"],
  },
  {
    slug: "bowl-voyage",
    title: "Bowl Voyage",
    tagline: "A Java cooking game with dishes from Rwanda, Côte d’Ivoire, Korea, and India.",
    year: "2025",
    sort: 2025.04,
    tier: "archive",
    visibility: "public",
    role: "Co-developer",
    team: "4-person team, Introduction to Computer Science (Java)",
    status: "completed",
    statusLabel: "Course project",
    categories: ["Software", "Coursework", "Just for fun"],
    tools: ["Java", "Object-oriented design", "Sprites & animation", "Sound effects"],
    links: [],
    challenge: "Making customers, recipes, and scoring feel alive in plain Java.",
    learned: "Code reviews catch the bugs you stop seeing.",
    summary: "A cooking simulation game built by a team of four: players cook traditional dishes from four countries for incoming customers. We built the graphics, animations, sound effects, customer interactions, and scoring with object-oriented Java.",
    story: [
      { type: "text", title: "The idea", body: ["We wanted a game that celebrated food from our own backgrounds. Bowl Voyage serves dishes from Rwanda, Côte d’Ivoire, Korea, and India."] },
      { type: "list", title: "What we built", items: [
        "Interactive graphics, animations, and sound effects",
        "Game logic for customers, orders, and scoring",
        "Object-oriented structure in Java",
        "Iterative testing and code reviews as a team of four",
      ] },
    ],
    artifacts: [],
    bench: { note: "The project that proved I like building playful things.", sticker: "4 cuisines" },
    needs: ["Gameplay screenshots or a short screen recording", "Repository link (if it can be public)", "Your specific part of the code", "Final presentation"],
  },
  {
    slug: "virginia-tech-flume",
    title: "Flume experiments at Virginia Tech",
    tagline: "Measuring how water moves before trying to move it anywhere.",
    year: "2023",
    sort: 2023.07,
    tier: "archive",
    visibility: "public",
    role: "TechGirls participant, RIVERS course",
    team: "Small student team, Civil & Environmental Engineering lab",
    status: "completed",
    statusLabel: "Program project",
    categories: ["Water", "Coursework"],
    tools: ["Acoustic Doppler velocimeter (ADV)", "Excel", "Python (first exposure)"],
    cover: { src: "/images/techgirls-virginia-tech.jpg", alt: "Sonia on the Virginia Tech campus at sunset" },
    links: [],
    challenge: "Comparing messy lab data to clean theory.",
    learned: "My first Python, and my first time trusting data over intuition.",
    summary: "In the TechGirls RIVERS course, I ran flume experiments measuring flow velocity with an acoustic Doppler velocimeter, water depth, and sediment transport across pump settings and slopes, then compared the results to theory.",
    story: [
      { type: "list", title: "What we did", items: [
        "Measured flow velocity (ADV), depth, and sediment transport in a lab flume",
        "Varied pump frequency and channel slope",
        "Processed the data and compared it to fluid-dynamics theory",
        "Wrote my first Python for data analysis",
      ] },
    ],
    artifacts: [{ kind: "certificate", label: "TechGirls 2023 certificate of completion", src: "/images/cert-techgirls-2023.jpg", href: "/images/cert-techgirls-2023.jpg" }],
    bench: { note: "Where water engineering stopped being abstract.", sticker: "RIVERS" },
    needs: ["Lab photo (LinkedIn education media has one)", "Any plots from the experiments"],
  },
  {
    slug: "blake-quarterly-cover",
    title: "Blake Quarterly, Summer 2025 cover",
    tagline: "A cover for an academic journal on William Blake.",
    year: "2025",
    sort: 2025.07,
    tier: "archive",
    visibility: "public",
    role: "Cover designer (Editorial Assistant Intern)",
    status: "completed",
    statusLabel: "Published",
    categories: ["Design"],
    tools: ["Adobe InDesign", "Typography"],
    cover: { src: "/images/blake-cover.jpg", alt: "Blake: An Illustrated Quarterly Summer 2025 cover" },
    links: [],
    challenge: "Keeping type readable over detailed artwork.",
    learned: "Restraint matters most when the source material is already strong.",
    summary: "The Summer 2025 cover of Blake/An Illustrated Quarterly (Vol. 59, No. 1): two Blake paintings joined by one translucent band carrying the title, season, and volume.",
    story: [
      { type: "text", title: "The brief", body: ["The journal needed a cover for Vol. 59, No. 1 that let Blake’s art lead. I stacked two of his paintings and joined them with a single translucent band for the title, season, and volume. The artwork is William Blake’s; the layout and type are mine."] },
      { type: "gallery", title: "Cover and internship", images: [
        { src: "/images/blake-cover.jpg", alt: "Blake Quarterly cover", caption: "Vol. 59, No. 1" },
        { src: "/images/rcl-presentation.jpg", alt: "Sonia with library colleagues at her internship presentation", caption: "End-of-internship presentation" },
      ] },
    ],
    artifacts: [{ kind: "publication", label: "Cover (Vol. 59, No. 1)", src: "/images/blake-cover.jpg", href: "/images/blake-cover.jpg" }],
    bench: { note: "Engineering student, journal cover. Both true.", sticker: "Vol. 59" },
    related: { experience: ["rcl"] },
    needs: ["Link to the published issue online"],
  },
];

export const publicProjects = projects.filter((p) => p.visibility === "public");
export const getProject = (slug: string) => publicProjects.find((p) => p.slug === slug);
